version: '2.1'

services:
  php-server:
    image: php-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    environment:
      - MONGO_HOST=mongodb:27017
      - MONGO_DATABASE=php
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db/
    ports:
      - 27017:27017
