version: '2.1'

services:
  php-server:
    image: php-server
    build: .
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb_data:/var/lib/mongodb
    ports:
      - 27017:27017

volumes:
  mongodb_data:
    driver: local